[theme]
base = "dark"
primaryColor = "#3BAFDA"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#161B22"
textColor = "#FFFFFF"

[app]
transaction_cost_bps = 5
slippage_bps = 5
target_vol_annual = 0.12
kelly_clip = 0.5
hard_dd = -0.08

[defaults]
rsi_window = 14
rsi_buy = 30
rsi_sell = 70
ma_fast = 20
ma_mid = 50
ma_slow = 100
bb_window = 20
bb_std = 2.0
atr_window = 14
atr_k_trail_bull = 3.0
atr_k_trail_side = 2.0
atr_k_trail_bear = 1.5
w_rsi = 0.2
w_ma = 0.25
w_bb = 0.15
w_atr = 0.2
w_breakout = 0.1
w_sent = 0.1
score_buy = 0.6
score_sell = -0.6
percentile_mode = true
percentile_window = 90
